"""
Django settings for django_portfolio project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/#__file__
"""

from pathlib import Path
# Importamos 'os' para manejar rutas, aunque 'Path' ya está definido. 
# Para compatibilidad con la estructura tradicional de Django:
import os 


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Importante: BASE_DIR apunta a la carpeta principal de tu proyecto ('/home/pyjango/django_portfolio').


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--5uicr%c%@)*@-je*q(jp5al908j&y_y0zu4k$k&!f%$)r9p=q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# line added due some change in the server
ALLOWED_HOSTS = ['pyjango.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'portfolio',
]

# ... [MIDDLEWARE - Sin cambios] ...

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_portfolio.urls'

# --- SECCIÓN CRÍTICA DE MODIFICACIÓN ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # **CAMBIO CRÍTICO:** Agregamos BASE_DIR a la lista DIRS. 
        # Esto le dice a Django que busque plantillas ('data_hub.html') 
        # en la carpeta raíz del proyecto, además de las carpetas 'templates' de las apps.
        'DIRS': [os.path.join(BASE_DIR)], 
        'APP_DIRS': True, # Esto mantiene la búsqueda dentro de las carpetas 'templates' de las apps.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# --- FIN DE SECCIÓN CRÍTICA ---


WSGI_APPLICATION = 'django_portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
       'ENGINE': 'django.db.backends.mysql',
       'NAME': 'pyjango$default',
       'USER': 'pyjango',
       'PASSWORD': 'Brainstorm13',
       'HOST':'pyjango.mysql.pythonanywhere-services.com',
       'PORT':'3306',
    }
}
# Importante: Esta sección de DATABASES es crucial para tu conexión MySQL.


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_ROOT = BASE_DIR / 'MEDIA'
MEDIA_URL = '/public/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
